### ISSUE TITLE
Acquire metadata from Bioportal pulls about which properties include the labels and descriptions

### ISSUE THREAD

**Issue by debuos512** [bio-ontology-research-group/aberowl-sync#2]

**Comment by debuos512** [comment]
@leechuck Where does the Bioportal API tell you which property includes the label/description etc? http://data.bioontology.org/ontologies/GO/submissions

You seem to be able to retrieve all the classes etc with labels in a standard structure but not see where they are in the actual ontology (that I can find)

**Comment by leechuck** [comment]
According to
http://data.bioontology.org/documentation#OntologySubmission, there
should be a synonymProperty and definitionProperty; it may be empty when
it defaults to http://www.w3.org/2004/02/skos/core#prefLabel and
http://www.w3.org/2004/02/skos/core#definition.

R

**Comment by leechuck** [comment]
If this does not work (does not seem like it does, maybe it's only
supported by their SPARQL interface), there is a reasonable list of
defaults:

For label:

rdfs:label (http://www.w3.org/2000/01/rdf-schema#label)
skos:prefLabel (http://www.w3.org/2004/02/skos/core#prefLabel)
IAO:editor preferred term (http://purl.obolibrary.org/obo/IAO_0000111)

For synonyms:

http://www.w3.org/2004/02/skos/core#altLabel
IAO:alternative term (http://purl.obolibrary.org/obo/IAO_0000118)
http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
http://www.geneontology.org/formats/oboInOwl#hasSynonym
http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym

For definitions:

IAO:definition (http://purl.obolibrary.org/obo/IAO_0000115)
skos:definition (http://www.w3.org/2004/02/skos/core#definition)
Dublin Core description: http://purl.org/dc/elements/1.1/description
http://www.geneontology.org/formats/oboInOwl#hasDefinition

R

**Comment by debuos512** [comment]
For posterity, the label count over the repository before adding alternative label sources to RDFS Label is: 3,195,704

**Comment by debuos512** [comment]
TODO seperate synonyms/label/description indexing field (have to do weighted search i guess) when established that this works

**Comment by debuos512** [comment]
New label count: 4,338,906
Definition count: 275,781

**Comment by leechuck** [comment]
Duplicate
